### ISSUE TITLE
Wrong Image when opening lightbox

### ISSUE THREAD

**Issue by IrvingArmenta** [mreq/slick-lightbox#57]
Hello, thanks for this amazing plugin. 

I'll try to explain my Issue: 

When I click on an image for the lightbox function, I get another image to show up, instead of the one I clicked, even though the "href" is different, I keep getting the same image as before.

I'm using this 
```
https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.7.1/slick.min.js
https://cdnjs.cloudflare.com/ajax/libs/slick-lightbox/0.2.10/slick-lightbox.min.js
```

and this in the html file with a <script> tag

```
$(document).ready(function() {
      $('#eventCarousel').slick({
        prevArrow: '<span class="slick-prev">Previous</span>',
        nextArrow: '<span class="slick-next">Next</span>',
        slidesToShow: 5,
        infinite: true,
        dots: false,
        appendArrows: $('.arrows-wrap'),
        autoplay: true,
        mobilefirst: true,
        responsive: [
          {
            breakpoint: 1024,
            settings: {
              slidesToShow: 3,
              slidesToScroll: 3,
              infinite: true,
            }
          },
          {
            breakpoint: 600,
            settings: {
              slidesToShow: 2,
              slidesToScroll: 2
            }
          },
          {
            breakpoint: 480,
            settings: {
              slidesToShow: 1,
              slidesToScroll: 1
            }
          }
        ]
      });
      $('#eventCarousel').slickLightbox({
        navigateByKeyboard  : true
      });
    });
```
This is the HTML for the carousel: 

```
<div id="eventCarousel">
              <div class="item">
                <a style="display: block" href="http://jonvilma.com/images/mountain-6.jpg">1</a>
              </div>
              <div class="item">
                <a style="display: block" href="https://www.vancouvertrails.com/images/photos/goat-mountain-4.jpg">2</a>
              </div>
              <div class="item">
                <h4>3</h4></div>
              <div class="item">
                <h4>4</h4></div>
              <div class="item">
                <h4>5</h4></div>
              <div class="item">
                <h4>6</h4></div>
              <div class="item">
                <h4>7</h4></div>
              <div class="item">
                <h4>8</h4></div>
              <div class="item">
                <h4>9</h4></div>
              <div class="item">
                <h4>10</h4></div>
            </div>
```

It works fine at first, but when the carousel loops one time, I click on the slide with number 1 and I get the image from the slide with number 2, that is the issue. 

Any idea what can it be?

**Comment by othbert** [comment]
Hi @IrvingArmenta, I had the same issue I think.

The reason for me was due to the incorrect calculation of the image to show, when the lightbox was clicked. There is an event handler for the click event, 'click.slicklightbox' that is assigned in the constructor. Within the handling of the click, the code gets a group of the slick slides, but filtering out the clones. (method name is: filterOutSlickClones)

My fix, as I couldn't find a "by the book" way to override this method was simply to modify the code inline. (The use of this slicklightbox is just temporary too, but this means killing your upgrade path for new releases).

I checked if the clicked item's parent was a clone (parent made sense in this instance with the structure of the created carousel), determined the URL from the item (there were unique images in the carousel only), then filtered the pruned-of-clones items by the URL to get the reference as if the user clicked on the original slide.

So, in the constructor, between: 
`$items = slickLightbox.filterOutSlickClones(slickLightbox.$element.find(slickLightbox.options.itemSelector));`

and 

`return slickLightbox.init($items.index($clickedItem));`

I added:

`
//get the correct index whether the item is a clone or not!
if ($clickedItem.parent().hasClass('slick-cloned')) {
    var clickedUrlToMatch = $clickedItem.attr('href');
    $clickedItem = $items.filter(function() {
        return ($(this).attr('href') === clickedUrlToMatch);
    });
}
`

Hope that helps!

**Comment by mreq** [comment]
Thanks for the report @IrvingArmenta and the fix @othbert! Implemented your workaround in v0.2.12

**Comment by reiddraper** [comment]
I just hit this same issue as well. Adding an `href` attribute to my images fixed it. I was previously specifying `src: 'src'`.

**Comment by thedailycommute** [comment]
I just started playing with the lightbox today, and hit exactly the same problem when using an existing slider (with cloned slides). My solution (until a fix is added) was to adjust the `handlePossibleCloneClick` function like this:
<pre><code>
SlickLightbox.prototype.handlePossibleCloneClick = function ($clickedItem, $items) {
    if (!this.elementIsSlick()) {
        return $clickedItem;
    }
    if (!$clickedItem.closest('.slick-slide').hasClass('slick-cloned')) {
        return $clickedItem;
    }
    _var attr = 'href';
    if (typeof this.options.src === 'string') {
        attr = this.options.src;
    }
    var value = $clickedItem.attr(attr);
    return $items.filter(function () {
        return $(this).attr(attr) === value;
    }).first();
};
</code></pre>

This way the "src" option is correctly used (if it's an attribute), and the default 'href' otherwise.
